USE customer_behavior;
-- what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
-- which customers used discount but still spent more than average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
  -- what are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) As avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
-- compare the average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;-- compare the average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Do subcribed customers spend more? compare average spend and total revenue between subcribers and non subcribers
SELECT subscription_status,
COUNT (customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue;

-- Which 5 products have the high percentages of purchase with discount applied
SELECT item_purchased
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;USE customer_behavior;
-- what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
-- which customers used discount but still spent more than average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
  -- what are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) As avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
-- compare the average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;-- compare the average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Do subcribed customers spend more? compare average spend and total revenue between subcribers and non subcribers
SELECT subscription_status,
COUNT (customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue;

-- Which 5 products have the high percentages of purchase with discount applied
SELECT item_purchased
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;USE customer_behavior;
-- what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;
-- which customers used discount but still spent more than average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);
  -- what are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) As avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
-- compare the average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;-- compare the average purchase amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Do subcribed customers spend more? compare average spend and total revenue between subcribers and non subcribers
SELECT subscription_status,
COUNT (customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue;

-- Which 5 products have the high percentages of purchase with discount applied
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Segment customers into New, Returning and LOyal based on their previousnpurchases and show the count of segment
with customer_type as(
SELECT customer_id, previous_purchases,
CASE
  WHEN previous_purchases= 1 THEN 'NEW'
  WHEN previous_purchases between 2 AND 10 THEN 'Returning'
  ELSE 'Loyal'
  END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) as "Number of customers"
FROM customer_type
GROUP BY customer_segment

--Which are the top 3 purchase products within each category?
with item_count as(
SELECT category, 
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER () over(partition by category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subcribe?

SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

-- WHat is the revenue contribution of each age group

SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;